### ISSUE TITLE
The cursor and where the pixels are placed are misaligned 

### ISSUE THREAD

**Issue by labbo-lab** [MaxBittker/sandspiel-studio#143]
(doesn't seem to happen in mega and big)

**Comment by labbo-lab** [comment]
nevermind, it happens in all of them, but its most noticeable in small I think

**Comment by TodePond** [comment]
There's currently some hacky adjustment going on to try to avoid this
If I remove the adjustment, this is what happens when you place a single sand pixel in each corner: 
![image](https://user-images.githubusercontent.com/15892272/197737919-cb25db11-a32a-4e96-be0a-d4ee6116c43b.png)

Seems to be more of an issue on the left/top sides

**Comment by TodePond** [comment]
Fixed - it wasn't factoring in the border when calculating brush position
